[
  {
    xAxis: "AdV",
    keys: ["AdV"],
    AdV: 440,
  },
  {
    xAxis: "Flu A",
    keys: ["Flu A"],
    "Flu A": 422,
  },
  {
    xAxis: "Flu B",
    keys: ["Flu B"],
    "Flu B": 441,
  },
  {
    xAxis: "HRV",
    keys: ["HRV"],
    HRV: 763,
  },
  {
    xAxis: "MPV",
    keys: ["MPV"],
    MPV: 121,
  },
  {
    xAxis: "PIV",
    keys: ["PIV"],
    PIV: 178,
  },
  {
    xAxis: "RSV",
    keys: ["RSV"],
    RSV: 512,
  },
  {
    xAxis: "SARS-CoV-2",
    keys: [
      "E gene,N gene(SARS-CoV-2)",
      "E gene,N gene,RdRP/S gene(SARS-CoV-2)",
      "E gene,RdRP gene(2019-nCoV)",
      "E gene,RdRP/S gene(SARS-CoV-2)",
      "N gene(SARS-CoV-2)",
      "N gene,RdRP/S gene(SARS-CoV-2)",
      "RdRP gene(2019-nCoV)",
      "RdRP/S gene(SARS-CoV-2)",
    ],
    "E gene,N gene(SARS-CoV-2)": 64,
    "E gene,N gene,RdRP/S gene(SARS-CoV-2)": 1628,
    "E gene,RdRP gene(2019-nCoV)": 8,
    "E gene,RdRP/S gene(SARS-CoV-2)": 59,
    "N gene(SARS-CoV-2)": 42,
    "N gene,RdRP/S gene(SARS-CoV-2)": 57,
    "RdRP gene(2019-nCoV)": 2,
    "RdRP/S gene(SARS-CoV-2)": 61,
  },
  {
    xAxis: "SARS-CoV-3",
    keys: [
      "E gene,N gene(SARS-CoV-2)",
      "E gene,N gene,RdRP/S gene(SARS-CoV-2)",
      "E gene,RdRP gene(2019-nCoV)",
      "E gene,RdRP/S gene(SARS-CoV-2)",
      "N gene(SARS-CoV-2)",
      "N gene,RdRP/S gene(SARS-CoV-2)",
      "RdRP gene(2019-nCoV)",
      "RdRP/S gene(SARS-CoV-2)",
    ],
    "E gene,N gene(SARS-CoV-2)": 10,
    "E gene,N gene,RdRP/S gene(SARS-CoV-2)": 20,
    "E gene,RdRP gene(2019-nCoV)": 30,
    "E gene,RdRP/S gene(SARS-CoV-2)": 40,
    "N gene(SARS-CoV-2)": 50,
    "N gene,RdRP/S gene(SARS-CoV-2)": 60,
    "RdRP gene(2019-nCoV)": 70,
    "RdRP/S gene(SARS-CoV-2)": 80,
  },
  {
    xAxis: "SARS-CoV-2 Presumptive",
    keys: ["SARS-CoV-2 Presumptive"],
    "SARS-CoV-2 Presumptive": 36,
  },
];
